name: Advanced Trivy Scan

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t vulnerable-image .

      # Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release

          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
          gpg --dearmor | \
          sudo tee /usr/share/keyrings/trivy.gpg > /dev/null

          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | \
          sudo tee /etc/apt/sources.list.d/trivy.list

          sudo apt-get update
          sudo apt-get install -y trivy

      # CVE Scan
      - name: CVE Scan
        run: |
          trivy image --severity CRITICAL,HIGH vulnerable-image

      # Secret Scan
      - name: Secret Scan
        run: |
          trivy image --scanners secret vulnerable-image

      # Misconfiguration Scan
      - name: Misconfiguration Scan
        run: |
          trivy config .

      # Generate SARIF report
      - name: Generate SARIF Report
        run: |
          trivy image \
            --format sarif \
            --output trivy-results.sarif \
            vulnerable-image

      # Upload SARIF report to GitHub Security
      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
